// app/layout.tsx (or wherever your RootLayout is located)
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ReduxProvider from './provider/redux_provider'; // Adjust the import path as necessary
import './globals.css';

import Header from "./component/navbar";
import Footer from "./component/footer";


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <ReduxProvider>
      <body className="bg-white">
        <Header />
        {children}
        <Footer />
      </body>
      </ReduxProvider>
    </html>
  );
}